name: build

on: [push, pull_request]

jobs:
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build burn
        run: |
          cl source/burn.c source/dos.c
      - name: build julia
        run: |
          cl source/julia.c source/dos.c
      - name: build mandelbrot
        run: |
          cl source/mandelbrot.c source/dos.c
      - name: build plasma
        run: |
          cl source/plasma.c source/dos.c
      - name: build raycast
        run: |
          cl source/raycast.c source/dos.c
      - name: build rotozoom
        run: |
          cl source/rotozoom.c source/dos.c
      - name: build sound
        run: |
          cl source/sound.c source/dos.c
      - name: build stranded
        run: |
          cl source/stranded.c source/dos.c
      - name: build tracker
        run: |
          cl source/tracker.c source/dos.c
      - name: build tunnel
        run: |
          cl source/tunnel.c source/dos.c
      - name: build voxel
        run: |
          cl source/voxel.c source/dos.c
  build-windows-tcc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: build burn
        run: |
          tcc/tcc source/burn.c source/dos.c
      - name: build julia
        run: |
          tcc/tcc source/julia.c source/dos.c
      - name: build mandelbrot
        run: |
          tcc/tcc source/mandelbrot.c source/dos.c
      - name: build plasma
        run: |
          tcc/tcc source/plasma.c source/dos.c
      - name: build raycast
        run: |
          tcc/tcc source/raycast.c source/dos.c
      - name: build rotozoom
        run: |
          tcc/tcc source/rotozoom.c source/dos.c
      - name: build sound
        run: |
          tcc/tcc source/sound.c source/dos.c
      - name: build stranded
        run: |
          tcc/tcc source/stranded.c source/dos.c
      - name: build tracker
        run: |
          tcc/tcc source/tracker.c source/dos.c
      - name: build tunnel
        run: |
          tcc/tcc source/tunnel.c source/dos.c
      - name: build voxel
        run: |
          tcc/tcc source/voxel.c source/dos.c
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build burn
        run: |
          clang -o burn.bin source/burn.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build julia
        run: |
          clang -o julia.bin source/julia.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build mandelbrot
        run: |
          clang -o mandelbrot.bin source/mandelbrot.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build plasma
        run: |
          clang -o plasma.bin source/plasma.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build raycast
        run: |
          clang -o raycast.bin source/raycast.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build rotozoom
        run: |
          clang -o rotozoom.bin source/rotozoom.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build sound
        run: |
          clang -o sound.bin source/sound.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build stranded
        run: |
          clang -o stranded.bin source/stranded.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build tracker
        run: |
          clang -o tracker.bin source/tracker.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build tunnel
        run: |
          clang -o tunnel.bin source/tunnel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build voxel
        run: |
          clang -o voxel.bin source/voxel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build burn
        run: |
          gcc -o burn.bin source/burn.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build julia
        run: |
          gcc -o julia.bin source/julia.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build mandelbrot
        run: |
          gcc -o mandelbrot.bin source/mandelbrot.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build plasma
        run: |
          gcc -o plasma.bin source/plasma.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build raycast
        run: |
          gcc -o raycast.bin source/raycast.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build rotozoom
        run: |
          gcc -o rotozoom.bin source/rotozoom.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build sound
        run: |
          gcc -o sound.bin source/sound.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build stranded
        run: |
          gcc -o stranded.bin source/stranded.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build tracker
        run: |
          gcc -o tracker.bin source/tracker.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build tunnel
        run: |
          gcc -o tunnel.bin source/tunnel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build voxel
        run: |
          gcc -o voxel.bin source/voxel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
