name: build

on: [push, pull_request]

jobs:
  build-windows-msvc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build burn
        run: |
          cl source/burn.c source/dos.c
      - name: build edit
        run: |
          cl source/edit.c source/dos.c
      - name: build julia
        run: |
          cl source/julia.c source/dos.c
      - name: build mandelbrot
        run: |
          cl source/mandelbrot.c source/dos.c
      - name: build plasma
        run: |
          cl source/plasma.c source/dos.c
      - name: build raycast
        run: |
          cl source/raycast.c source/dos.c
      - name: build rotozoom
        run: |
          cl source/rotozoom.c source/dos.c
      - name: build sound
        run: |
          cl source/sound.c source/dos.c
      - name: build stranded
        run: |
          cl source/stranded.c source/dos.c
      - name: build tracker
        run: |
          cl source/tracker.c source/dos.c
      - name: build tunnel
        run: |
          cl source/tunnel.c source/dos.c
      - name: build voxel
        run: |
          cl source/voxel.c source/dos.c
  build-windows-msvc-cpp:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build burn
        run: |
          cl /Tp source/burn.c /Tp source/dos.c
      - name: build edit
        run: |
          cl /Tp source/edit.c /Tp source/dos.c
      - name: build julia
        run: |
          cl /Tp source/julia.c /Tp source/dos.c
      - name: build mandelbrot
        run: |
          cl /Tp source/mandelbrot.c /Tp source/dos.c
      - name: build plasma
        run: |
          cl /Tp source/plasma.c /Tp source/dos.c
      - name: build raycast
        run: |
          cl /Tp source/raycast.c /Tp source/dos.c
      - name: build rotozoom
        run: |
          cl /Tp source/rotozoom.c /Tp source/dos.c
      - name: build sound
        run: |
          cl /Tp source/sound.c /Tp source/dos.c
      - name: build stranded
        run: |
          cl /Tp source/stranded.c /Tp source/dos.c
      - name: build tracker
        run: |
          cl /Tp source/tracker.c /Tp source/dos.c
      - name: build tunnel
        run: |
          cl /Tp source/tunnel.c /Tp source/dos.c
      - name: build voxel
        run: |
          cl /Tp source/voxel.c /Tp source/dos.c
  build-windows-tcc:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: build burn
        run: |
          tcc/tcc source/burn.c source/dos.c
      - name: build edit
        run: |
          tcc/tcc source/edit.c source/dos.c
      - name: build julia
        run: |
          tcc/tcc source/julia.c source/dos.c
      - name: build mandelbrot
        run: |
          tcc/tcc source/mandelbrot.c source/dos.c
      - name: build plasma
        run: |
          tcc/tcc source/plasma.c source/dos.c
      - name: build raycast
        run: |
          tcc/tcc source/raycast.c source/dos.c
      - name: build rotozoom
        run: |
          tcc/tcc source/rotozoom.c source/dos.c
      - name: build sound
        run: |
          tcc/tcc source/sound.c source/dos.c
      - name: build stranded
        run: |
          tcc/tcc source/stranded.c source/dos.c
      - name: build tracker
        run: |
          tcc/tcc source/tracker.c source/dos.c
      - name: build tunnel
        run: |
          tcc/tcc source/tunnel.c source/dos.c
      - name: build voxel
        run: |
          tcc/tcc source/voxel.c source/dos.c
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: brew install sdl2 glew
      - name: build burn
        run: |
          clang source/burn.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build edit
        run: |
          clang source/edit.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build julia
        run: |
          clang source/julia.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build mandelbrot
        run: |
          clang source/mandelbrot.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build plasma
        run: |
          clang source/plasma.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build raycast
        run: |
          clang source/raycast.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build rotozoom
        run: |
          clang source/rotozoom.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build sound
        run: |
          clang source/sound.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build stranded
        run: |
          clang source/stranded.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build tracker
        run: |
          clang source/tracker.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build tunnel
        run: |
          clang source/tunnel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
      - name: build voxel
        run: |
          clang source/voxel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -framework OpenGL -lpthread
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
          sudo apt-get install -qq libglew-dev
      - name: build burn
        run: |
          gcc source/burn.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build edit
        run: |
          gcc source/edit.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build julia
        run: |
          gcc source/julia.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build mandelbrot
        run: |
          gcc source/mandelbrot.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build plasma
        run: |
          gcc source/plasma.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build raycast
        run: |
          gcc source/raycast.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build rotozoom
        run: |
          gcc source/rotozoom.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build sound
        run: |
          gcc source/sound.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build stranded
        run: |
          gcc source/stranded.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build tracker
        run: |
          gcc source/tracker.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build tunnel
        run: |
          gcc source/tunnel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
      - name: build voxel
        run: |
          gcc source/voxel.c source/dos.c `sdl2-config --libs --cflags` -lGLEW -lGL -lm -lpthread
  build-wasm:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: robinraju/release-downloader@v1.2
        with:
          repository: "mattiasgustavsson/dos-like"
          tag: "wasm-env"
          fileName: "dos-like-wasm-build-env-win.zip"
      - name: build burn
        run: |
          7z e dos-like-wasm-build-env-win.zip
          wasm\node wasm\wajicup.js source/rotozoom.c source/dos.c rotozoom.html
